/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Student;

import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTabbedPane;
import java.awt.*;
import java.awt.event.*;
import java.util.Date;

/**
 *
 * @author PKS-15
 */
public class Testprohod extends javax.swing.JFrame {
    JLabel label1;
    JLabel label2;
    JRadioButton rad1;
    JRadioButton rad2;
    JRadioButton rad3;
    double kolvo = 0;
    ButtonGroup grp;
    double res = 0;
    String login;
    /**
     * Creates new form Testprohod
     */
     public Testprohod() {
        initComponents();
         try{
          String Url = "jdbc:mysql://localhost/protest?autoReconnect=true&useSSL=false";
          Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(Url, "root", "");
           Statement stmt = conn.createStatement();
           ResultSet resultSet = stmt.executeQuery("SELECT NaimTest FROM protest.Test");
           while(resultSet.next()){jComboBox1.addItem(resultSet.getString("NaimTest")); }        
          conn.close();
      }
      catch(Exception e)
      {
          System.err.println(e.getMessage());
      }
     }
     
    public Testprohod(String login) {
        initComponents();
         try{
          String Url = "jdbc:mysql://localhost/protest?autoReconnect=true&useSSL=false";
          Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(Url, "root", "");
           Statement stmt = conn.createStatement();
           ResultSet resultSet = stmt.executeQuery("SELECT NaimTest FROM protest.Test");
           while(resultSet.next()){jComboBox1.addItem(resultSet.getString("NaimTest")); }        
          conn.close();
      }
      catch(Exception e)
      {
          System.err.println(e.getMessage());
      }
        setlogin(login);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Задача: выполните тест");

        jButton2.setForeground(new java.awt.Color(255, 0, 255));
        jButton2.setText("Выполнить");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(255, 0, 204));
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jComboBox1.setForeground(new java.awt.Color(255, 0, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 51));
        jLabel3.setText("Выберите тест:");

        jButton1.setForeground(new java.awt.Color(255, 0, 255));
        jButton1.setText("Начать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1)))))
                    .addComponent(jButton2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(471, 474));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
public String getlogin(){
        return login;
    }
public void setlogin(String login){
        this.login = login;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int id = jComboBox1.getSelectedIndex()+1;
     String group = null;
     int stud = 1;
     String test = null;
     int idt = 1;
     int ocenka = 0;
        try{
          String Url = "jdbc:mysql://localhost/protest?autoReconnect=true&useSSL=false";
          Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(Url, "root", "");
           Statement stmt = conn.createStatement();
           String query1 = "insert into protest.result_test("
                   + "result_test.idTest,result_test.idStudent," +
            "result_test.NaimTesta,result_test.Group"
                  + ",result_test.Ocenka,result_test.Date_vip_test " +
        ") values(?,?,?,?,?,?)";
    ResultSet resSet = stmt.executeQuery("SELECT `group`.Groupa FROM `group`, student where student.login = '" +getlogin()+ "'");
            while(resSet.next()){
              group = resSet.getString("Groupa");
            }

            ResultSet resSet2 = stmt.executeQuery("SELECT idStudent FROM student where student.login = '"+ getlogin()+"'");
             while(resSet2.next()){
              stud = resSet2.getInt("idStudent");
            }
            ResultSet resSet3 = stmt.executeQuery("SELECT * FROM test where test.idTest = "+id);
            while(resSet3.next()){
              test = resSet3.getString("NaimTest");
              idt = resSet3.getInt("idTest");
            }
           Date data = new Date();
          ResultSet resSet0 = stmt.executeQuery("SELECT * FROM protest.result_test;");
            PreparedStatement preparedStat = conn.prepareStatement(query1);
          //  int rowCount = resSet0.getRow();
         // preparedStat.setInt(1, rowCount+1);
         double fin = (kolvo/res)*100;
           if (fin<= 25){
           ocenka = 2;
           }
           if (fin>= 50){
           ocenka = 3;
           }
           if (fin>= 75){
           ocenka = 4;
           }
           if (fin>= 100){
           ocenka = 5;
           }
            preparedStat.setInt(1, idt);
            preparedStat.setInt(2, stud);
            preparedStat.setString(3, test);
            preparedStat.setString(4, group);
            preparedStat.setDouble(5, ocenka);
            preparedStat.setDate(6, new java.sql.Date(data.getTime()));
            preparedStat.execute();
           
          JOptionPane.showMessageDialog(this,"Выполнено: " + (int)kolvo + " из " +(int)res+ ". Оценка " + ocenka );
          
          this.dispose();
            new Student(getlogin()).setVisible(true);
          conn.close();
      }
      catch(Exception e)
      {
          System.err.println(e.getMessage());
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int i = 0;
       int id = jComboBox1.getSelectedIndex()+1;
        try{
          String Url = "jdbc:mysql://localhost/protest?autoReconnect=true&useSSL=false";
          Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(Url, "root", "");
           Statement stmt = conn.createStatement();
           ResultSet resultSet = stmt.executeQuery("SELECT * FROM protest.test where test.idTest = "+"'"+id+"'");
            while(resultSet.next()){
           JOptionPane.showMessageDialog(this, resultSet.getString("Comment"),resultSet.getString("NaimTest"),JOptionPane.PLAIN_MESSAGE);}
            ResultSet resultSet2 = stmt.executeQuery("SELECT * FROM protest.voprosi where voprosi.Test_idTest = "+ "'"+id+"'");
           while(resultSet2.next()){
               i++;
               JPanel panel = new JPanel();
            panel.setLayout(null);
            label1 = new JLabel(String.format("Вопрос %d", i));
            label2 = new JLabel(resultSet2.getString(3));
            label1.setFont(new Font("Times new roman", 14, 14));
            label2.setFont(new Font("Times new roman", 14, 14));
            label1.setLocation(100, 20);
            label1.setSize(300, 10);
            label2.setLocation(100, 50);
            label2.setSize(300, 10);
            
            JRadioButton rad1 = new JRadioButton(resultSet2.getString(4));
            rad1.setLocation(100, 75);
            rad1.setSize(300, 20);
            JRadioButton rad2 = new JRadioButton(resultSet2.getString(5));
            rad2.setLocation(100, 100);
            rad2.setSize(300, 20);
            JRadioButton rad3 = new JRadioButton(resultSet2.getString(6));
            rad3.setLocation(100, 125);
            rad3.setSize(300, 20);
            if (resultSet2.getString(4).equals(resultSet2.getString(7))){
               rad1.addActionListener((e) -> {
                   kolvo++;
               });
               res++;
            }
            if (resultSet2.getString(5).equals(resultSet2.getString(7))){
               rad2.addActionListener((e) -> {
                   kolvo++;
               });
               res++;
            }
            if (resultSet2.getString(6).equals(resultSet2.getString(7))){
               rad3.addActionListener((e) -> {
                   kolvo++;
               });
               res++;
            }
            ButtonGroup grp = new ButtonGroup();
            grp.add(rad1);
            grp.add(rad2);
            grp.add(rad3);
            
            panel.add(label1);
            panel.add(label2);
            panel.add(rad1);
            panel.add(rad2);
            panel.add(rad3);
            
            // Добавление панели во вкладку 
            jTabbedPane1.addTab("<html><i>Задача №" + i, 
                             new ImageIcon("images/copy.png"), panel, "Нажмите " + i);
           }        
          conn.close();
      }
      catch(Exception e)
      {
          System.err.println(e.getMessage());
      }
    }//GEN-LAST:event_jButton1ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Testprohod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Testprohod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Testprohod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Testprohod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testprohod().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
